server:
  port: 9000

spring:
  application:
    name: docker-demo
  profiles:
#    active: dev
    active: '@maven.profile.active@'
  messages:
    basename: i18n/message
    encoding: UTF-8

logging:
  config: classpath:log/spring-log4j2-@maven.profile.active@.xml